### ISSUE TITLE
Class "cweagans\Composer\PatchEvents" not found

### ISSUE THREAD

**Issue by matsbla** [orakili/composer-drupal-info-file-patch-helper#1]
Thanks for the library, it is very useful!
However it suddenly stopped working, I now get this error:

```- Installing orakili/composer-drupal-info-file-patch-helper (1.0.1): Extracting archive
    Install of orakili/composer-drupal-info-file-patch-helper failed

In Plugin.php line 65:
                                                   
  [Error]                                          
  Class "cweagans\Composer\PatchEvents" not found 
```

**Comment by orakili** [comment]
Could you show your composer.json? This plugin requires [cweagans/composer-patches](https://packagist.org/packages/cweagans/composer-patches).

**Comment by matsbla** [comment]
Yes, I have that one installed as well.
Attached is the json file!

[composer.zip](https://github.com/orakili/composer-drupal-info-file-patch-helper/files/10967364/composer.zip)

**Comment by orakili** [comment]
I ran `composer update` with the provided composer.json (without the `pantheon-upstreams/upstream-configuration`) and everything installed properly.

Maybe the composer cache is stale or something. You could try  deleting the `vendor` (and `.composer` if it exists) and run `composer update --no-cache` to see if that works.

**Comment by matsbla** [comment]
Thanks for the answer, I managed to fix this now, the problem was the order, I had to put pantheon-upstreams/upstream-configuration first
